### ISSUE TITLE
Non-square grid bug

### ISSUE THREAD

**Issue by perrygeo** [Turfjs/turf-square-grid#4] opened 2016-02-21 18:20 UTC
Installed with `npm install -g turf-cli` and I'm getting strange results from the command line interface.

This appears to work fine

```
$ turf squareGrid "[-40, -40, 40, 40]" 500 miles | geojson-summary
108 polygons
```

![40_500](https://cloud.githubusercontent.com/assets/1151287/13204418/ddda22c4-d8a5-11e5-8583-d34dcf5176da.png)

This (setting min/max latitude to -80/80) does not

```
$ turf squareGrid "[-40, -80, 40, 80]" 500 miles | geojson-summary
46 polygons
```

![80_500](https://cloud.githubusercontent.com/assets/1151287/13204419/f33dfd98-d8a5-11e5-973e-843a26a21932.png)

Haven't had a chance to debug but thought I might pose the question here to see if any had come across this and can explain the behavior.

**Comment by perrygeo** [comment] 2016-02-21 18:25
Very similar issue with `turf pointGrid`, perhaps related?

**Comment by dakk** [comment] 2016-03-29 14:02
Same problem here, I'm trying to generate a mapgrid of the entire world but I get some crazy geojson; inspecting the data, I've found invalid coordinates, like in the following feature:

``` json
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -180,
              79.57948946449265
            ],
            [
              -180,
              80.02900915312503
            ],
            [
              66407557842696860,
              80.02900915312503
            ],
            [
              66407557842696860,
              79.57948946449265
            ],
            [
              -180,
              79.57948946449265
            ]
          ]
        ]
      },
```

**Comment by dakk** [comment] 2016-03-29 15:21
The problem is here: https://github.com/Turfjs/turf-square-grid/blob/master/index.js#L26
Turf distance is calculating the distance between -180,-80 and 180,-80 that is near zero because it's the same point (turf-distance returns the correct value); then cell/1e-x return an incorrect very large value.

So, we need to calculate the xFraction with a different distance formula; I'm going to push the fix.

**Comment by tmcw** [comment] 2016-04-24 00:25
Fixed in https://github.com/Turfjs/turf-square-grid/pull/5

**Closed as completed by tmcw** 2016-04-24 00:25 UTC
